/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs2263hw01;

import java.io.IOException;
import java.util.*;

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.Button;
import javafx.scene.text.Text;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.geometry.Pos;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.input.MouseEvent;
import java.util.Vector;

public class App extends Application{
    @Override
    public void start(Stage primaryStage) throws Exception {

    }

    public static void main(String[] args) {
        Application.launch(args);
    }


}
